### ISSUE TITLE
Failed to ionstall hashtable

### ISSUE THREAD

**Issue by StefanoGitHub** [chad3814/node-hashtable#24]
Hi,
I tried to install this module but in my MacBook air (OS X 10.11.1, El Capitan) I got this error:

```
npm WARN package.json 2SUM@1.0.0 No repository field.
npm WARN package.json 2SUM@1.0.0 No README data
-
> hashtable@2.0.1 install /Users/Stefano/GoogleDrive/Algorithms/Code/Week6-2SUM_MedianMaintenance/node_modules/hashtable
> node-gyp configure build xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/Stefano/GoogleDrive/Algorithms/Code/Week6-2SUM_MedianMaintenance/node_modules/hashtable
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "hashtable"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! hashtable@2.0.1 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hashtable@2.0.1 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the hashtable package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls hashtable
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Stefano/GoogleDrive/Algorithms/Code/Week6-2SUM_MedianMaintenance/npm-debug.log
```

Any suggestion?
Thanks,
Stefano

p.s. I converter npm-debug.log in [npm-debug.txt](https://github.com/chad3814/node-hashtable/files/38446/npm-debug.txt) so that I could attach it here.

**Comment by chad3814** [comment]
you need to install the xcode command line tools, this module requires c++ compilation.
