### ISSUE TITLE
Build fails on OS X Yosemite (10.10.5) 

### ISSUE THREAD

**Issue by jorgedr94** [chad3814/node-hashtable#35]
Running npm install fails with the following error:

```
(venv) Jorges-MacBook-Pro:node_modules jorgedr$ npm install hashtable

> hashtable@2.0.2 install /Users/jorgedr/go-work/src/github.com/jorgedr94/block-chain/hackfest/node_modules/hashtable
> node-gyp configure build

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/native/src/hashtable.o
In file included from ../src/hashtable.cpp:1:
../src/hashtable.h:7:10: fatal error: 'tr1/unordered_map' file not found
#include <tr1/unordered_map>
         ^
1 error generated.
make: *** [Release/obj.target/native/src/hashtable.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/jorgedr/go-work/src/github.com/jorgedr94/block-chain/hackfest/node_modules/hashtable
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
npm WARN balance-transfer@0.0.1 No repository field.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "install" "hashtable"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! hashtable@2.0.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hashtable@2.0.2 install script 'node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hashtable package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hashtable
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hashtable
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jorgedr/go-work/src/github.com/jorgedr94/block-chain/hackfest/node_modules/npm-debug.log

```
[npm-debug.txt](https://github.com/chad3814/node-hashtable/files/783489/npm-debug.txt)

**Comment by jorgedr94** [comment]
Hmm.. this does not seem to be a an issue of the OS version, I actually upgraded to MAC OS Sierra 10.12.3 and I still get the same error.

**Comment by jorgedr94** [comment]
This is actually a duplicate of https://github.com/chad3814/node-hashtable/pull/31 . I forked the project with the fix and pulled a version of hashtable with that fixed and it worked.
