### ISSUE TITLE
Problems installing under Windows 7

### ISSUE THREAD

**Issue by simlu** [chad3814/node-hashtable#44]
I've tried installing VS and various net frameworks, playing with the system path - nothing.... Urg.

Note that this log is from a fork, but I get the same problem with this repo. Am I doing something wrong? Anyone got an idea?

`MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere. `

```
...
380 silly lifecycle hashtable-patch-valeriansaliou@2.1.5~install: Args: [ '/d /s /c', 'node-gyp configure build' ]
381 silly lifecycle hashtable-patch-valeriansaliou@2.1.5~install: Returned: code: 1  signal: null
382 info lifecycle hashtable-patch-valeriansaliou@2.1.5~install: Failed to exec install script
383 verbose unlock done using C:\Users\...\AppData\Roaming\npm-cache\_locks\staging-376f116635f8d794.lock for C:\Users\...\node_modules\.staging
384 silly rollbackFailedOptional Starting
385 silly rollbackFailedOptional Finishing
386 silly runTopLevelLifecycles Finishing
387 silly install printInstalled
388 verbose stack Error: hashtable-patch-valeriansaliou@2.1.5 install: `node-gyp configure build`
388 verbose stack Exit status 1
388 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
388 verbose stack     at emitTwo (events.js:106:13)
388 verbose stack     at EventEmitter.emit (events.js:191:7)
388 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
388 verbose stack     at emitTwo (events.js:106:13)
388 verbose stack     at ChildProcess.emit (events.js:191:7)
388 verbose stack     at maybeClose (internal/child_process.js:886:16)
388 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
389 verbose pkgid hashtable-patch-valeriansaliou@2.1.5
390 verbose cwd ...
391 error Windows_NT 6.1.7601
392 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "fast-ratelimit"
393 error node v6.10.3
394 error npm  v3.10.10
395 error code ELIFECYCLE
396 error hashtable-patch-valeriansaliou@2.1.5 install: `node-gyp configure build`
396 error Exit status 1
397 error Failed at the hashtable-patch-valeriansaliou@2.1.5 install script 'node-gyp configure build'.
397 error Make sure you have the latest version of node.js and npm installed.
397 error If you do, this is most likely a problem with the hashtable-patch-valeriansaliou package,
397 error not with npm itself.
397 error Tell the author that this fails on your system:
397 error     node-gyp configure build
397 error You can get information on how to open an issue for this project with:
397 error     npm bugs hashtable-patch-valeriansaliou
397 error Or if that isn't available, you can get their info via:
397 error     npm owner ls hashtable-patch-valeriansaliou
397 error There is likely additional logging output above.
398 verbose exit [ 1, true ]
```

**Comment by simlu** [comment]
Finally fixed this by installing `npm install -g windows-build-tools` with elevated privileges (Reference https://superuser.com/questions/1032689/how-do-i-add-vcbuild-exe-to-windows-10-w-o-visual-studio)
